# 改端口
server:
  port: 9090


# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dstimer?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # springboot2.6以上不开这个swagger会报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 开debug模式
logging:
  level:
    com:
      example:
        dstimer:
          mapper: debug

# 扫描Mybatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
